version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
